export default [
    { key: 'windowOpen', title: 'window联动' },
    { key: 'table', title: '表格' },
    { key: 'import', title: '导入' },
    { key: 'upfile', title: '上传图片' },
    { key: 'richEditor', title: '富文本编辑器' },
    { key: 'workFlow', title: '流程状态' },
    { key: 'calendar', title: '日期选择器' },
    { key: 'innerBox', title: '内页模板' },
    { key: 'supplier', title: '供应商内页' },
    { key: 'departCheck', title: '多选部门参照' },
    { key: 'departRadio', title: '单选部门参照' },
    { key: 'checkSupplier', title: '选择供应商参照' },
    { key: 'checkInventCode', title: '选择货品编码' },
    { key: 'checkCustomer', title: '选择客户' },
    { key: 'checkEmployee', title: '选择人员' },
    { key: 'checkProcess', title: '选择工序' },
    { key: 'warning', title: '警告提示框' },
    { key: 'alert', title: '确认操作框' },
    { key: 'upfileGroup', title: '上传文件组' },
    { key: 'treeTable', title: 'bom内页treeTable' },
    { key: 'roleSelect', title: '岗位管理' },
    { key: 'currencySet', title: '币种设置弹框'},
    { key: 'checkSupplierInput', title: '可输可选供应商'},
    { key: 'goodsAndReference', title: '发/退货参照'},
    { key: 'checkSaleOrder', title: '销售订单'},
    { key: 'checkboxInventory', title: '货品多选参照'},
    { key: 'inventoryCategory', title: '货品分类'},
    { key: 'changePageIndex', title: '分页'},
    { key: 'menu', title: '多级菜单'},
    { key: 'roleAuth', title: '岗位授权'},
    { key: 'postAuth', title: '职能授权'},
]
